Perform the following operations using Python on Movie data sets 
m. Create data subsets for different languages(Original Language). 
n. Merge two subsets 
o. Sort Data using customer ratings. 
p. Transposing Data 
q. Melting Data to long format 
r. Casting data to wide format

In [1]:
import pandas as pd

In [2]:
# load dataset
movies=pd.read_csv('../files/movies.csv')
movies.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [5]:
# Create data subsets for different languages (Original Language)

english_movies=movies[movies['original_language']=='en']
korean_movies=movies[movies['original_language']=='ko']

In [6]:
english_movies.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [7]:
korean_movies.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
1286,1286,39200000,Action Science Fiction Drama,http://snowpiercer-film.com/,110415,father son relationship child labour brothel w...,ko,Snowpiercer,In a future where a failed global-warming expe...,64.238688,...,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"AD 2031, the passengers in the train are the o...",Snowpiercer,6.7,2854,Chris Evans Song Kang-ho Ed Harris John Hurt T...,"[{'name': 'Johanna Ray', 'gender': 1, 'departm...",Bong Joon-ho
1518,1518,70000000,Fantasy Drama Horror Action Thriller,NaN,10253,giant snake korea building dagger south korea,ko,디워,"Based on the Korean legend, unknown creatures ...",4.822033,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,They've made our world their battleground,Dragon Wars: D-War,4.0,104,Jason Behr Robert Forster Aimee Garcia Chris M...,"[{'name': 'Steve Jablonsky', 'gender': 2, 'dep...",Shim Hyung-Rae
2521,2521,16000000,Action Adventure Drama Thriller,NaN,33196,helicopter beach loss of father giant wave tsu...,ko,해운대,"Man-sik and Yeon-hee, are unsure as to whether...",4.628525,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Tidal Wave,6.5,48,Park Joong-hoon Sol Kyung-gu Uhm Jung-hwa Ha J...,"[{'name': 'David S. Dranitzke', 'gender': 0, '...",Yoon Je-kyoon
2784,2784,0,History Drama War Action,NaN,407887,"korea fictionalized history operation ""trudy j...",ko,인천상륙작전,A squad of soldiers fight in the Korean War's ...,6.116436,...,110.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Odds Were 5000 to 1 … One was all They Nee...,Operation Chromite,5.8,29,Lee Jung-jae Liam Neeson Lee Beom-soo Jin Se-y...,"[{'name': 'John H. Lee', 'gender': 2, 'departm...",John H. Lee
2806,2806,0,Action Adventure Drama History War,NaN,11658,archaeologist korean war north korea south kor...,ko,태극기 휘날리며,"In 1950, in South Korea, shoe-shiner Jin-tae L...",9.572705,...,140.0,"[{""iso_639_1"": ""ko"", ""name"": ""\ud55c\uad6d\uc5...",Released,NaN,Tae Guk Gi: The Brotherhood of War,7.4,133,Jang Dong-gun Won Bin Lee Eun-ju Gong Hyung-ji...,"[{'name': 'Kang Je-gyu', 'gender': 0, 'departm...",Kang Je-gyu

In [8]:
# Merge two subsets
merged_movies=pd.concat([english_movies,korean_movies])
merged_movies.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [11]:
# Sort Data using customer ratings.

movies.columns.tolist()

['index',
 'budget',
 'genres',
 'homepage',
 'id',
 'keywords',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'vote_average',
 'vote_count',
 'cast',
 'crew',
 'director']

In [12]:
sorted_movies=movies.sort_values(by='popularity',ascending=False)
sorted_movies.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
546,546,74000000,Family Animation Adventure Comedy,http://www.minionsmovie.com/,211672,assistant aftercreditsstinger duringcreditssti...,en,Minions,"Minions Stuart, Kevin and Bob are recruited by...",875.581305,...,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Before Gru, they had a history of bad bosses",Minions,6.4,4571,Sandra Bullock Jon Hamm Michael Keaton Allison...,"[{'name': 'Christopher Meledandri', 'gender': ...",Kyle Balda
95,95,165000000,Adventure Drama Science Fiction,http://www.interstellarmovie.net/,157336,saving the world artificial intelligence fathe...,en,Interstellar,Interstellar chronicles the adventures of a gr...,724.247784,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Mankind was born on Earth. It was never meant ...,Interstellar,8.1,10867,Matthew McConaughey Jessica Chastain Anne Hath...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
788,788,58000000,Action Adventure Comedy,http://www.foxmovies.com/movies/deadpool,293660,anti hero mercenary marvel comic superhero bas...,en,Deadpool,Deadpool tells the origin story of former Spec...,514.569956,...,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Witness the beginning of a happy ending,Deadpool,7.4,10995,Ryan Reynolds Morena Baccarin Ed Skrein T.J. M...,"[{'name': 'Ronna Kress', 'gender': 1, 'departm...",Tim Miller
94,94,170000000,Action Science Fiction Adventure,http://marvel.com/guardians,118340,marvel comic spaceship space outer space orphan,en,Guardians of the Galaxy,"Light years from Earth, 26 years after being a...",481.098624,...,121.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,All heroes start somewhere.,Guardians of the Galaxy,7.9,9742,Chris Pratt Zoe Saldana Dave Bautista Vin Dies...,"[{'name': 'Craig Wood', 'gender': 2, 'departme...",James Gunn
127,127,150000000,Action Adventure Science Fiction Thriller,http://www.madmaxmovie.com/,76341,future chase post-apocalyptic dystopia australia,en,Mad Max: Fury Road,An apocalyptic story set in the furthest reach...,434.278564,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What a Lovely Day.,Mad Max: Fury Road,7.2,9427,Tom Hardy Charlize Theron Nicholas Hoult Hugh ...,"[{'name': 'Iain Smith', 'gender': 2, 'departme...",George Miller

In [15]:
# Transposing Data

transposed_movies=movies.head().T
transposed_movies.head()

,0,1,2,3,4
index,0,1,2,3,4
budget,237000000,300000000,245000000,250000000,260000000
genres,Action Adventure Fantasy Science Fiction,Adventure Fantasy Action,Action Adventure Crime,Action Crime Drama Thriller,Action Adventure Science Fiction
homepage,http://www.avatarmovie.com/,http://disney.go.com/disneypictures/pirates/,http://www.sonypictures.com/movies/spectre/,http://www.thedarkknightrises.com/,http://movies.disney.com/john-carter
id,19995,285,206647,49026,49529

In [17]:
# Melting Data to Long Format

melted_movies=pd.melt(movies,id_vars=['title','original_language'],var_name='attribute',value_name='value')
melted_movies.head()

                                      title original_language attribute value
0                                    Avatar                en     index     0
1  Pirates of the Caribbean: At World's End                en     index     1
2                                   Spectre                en     index     2
3                     The Dark Knight Rises                en     index     3
4                               John Carter                en     index     4

In [18]:
# Casting Data to Wide Format

casted_movies = melted_movies.pivot_table(index='original_language', 
                                          columns='attribute', 
                                          values='value', 
                                          aggfunc=lambda x: x.iloc[0] if x.dtype == 'O' else x.mean())
casted_movies.head()

attribute,budget,cast,crew,director,genres,homepage,id,index,keywords,original_title,...,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count
original_language,,,,,,,,,,,,,,,,,,,,,
af,3000000,Presley Chweneyagae Jerry Mofokeng Terry Pheto...,"[{'name': 'Moonyeenn Lee', 'gender': 0, 'depar...",Gavin Hood,Crime Drama,http://www.tsotsimovie.com/,868,3936,slum baby fight nudity leader,Tsotsi,...,"[{""name"": ""Movieworld Productions"", ""id"": 563}...","[{""iso_3166_1"": ""ZA"", ""name"": ""South Africa""}]",2005-08-18,9879971,94.0,"[{""iso_639_1"": ""af"", ""name"": ""Afrikaans""}, {""i...",Released,In this world... Redemption comes just once.,6.9,94
ar,0,Khalid Abdalla Dina Abdullah Dina Amer Magdy A...,"[{'name': 'Pierre Haberer', 'gender': 0, 'depa...",Jehane Noujaim,Documentary Drama History,http://www.thesquarefilm.com/,159037,4164,woman director,The Square,...,"[{""name"": ""Roast Beef Productions"", ""id"": 7266...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-07,0,88.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,What does it mean to risk your life for your i...,7.8,55
cn,36000000,Donnie Yen Lynn Hung Zhang Jin Patrick Tam Kar...,"[{'name': 'Kenji Kawai', 'gender': 2, 'departm...",Wilson Yip,Action Drama History,NaN,365222,1357,biography,葉問3,...,"[{""name"": ""Mandarin Films Distribution Co."", ""...","[{""iso_3166_1"": ""HK"", ""name"": ""Hong Kong""}]",2015-12-19,156844753,105.0,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,NaN,6.5,379
cs,0,Witney Carson Chehon Wespi-Tschopp Gary Daniel...,"[{'name': 'David Winters', 'gender': 2, 'depar...",David Winters,Drama Romance,https://www.facebook.com/eastsidestorymovie,357837,2906,dancing competition hotel florida dance teacher,Dancin' It's On,...,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-10-16,0,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Post Production,Dancin' Like You've Never Seen Before,4.3,2
da,14200000,Bryce Dallas Howard Isaach De Bankol\u00e9 Dan...,"[{'name': 'Lars von Trier', 'gender': 2, 'depa...",Lars von Trier,Drama,NaN,1951,2665,southern usa slavery duringcreditsstinger,Manderlay,...,"[{""name"": ""Zentropa Entertainments"", ""id"": 76}...","[{""iso_3166_1"": ""DK"", ""name"": ""Denmark""}, {""is...",2005-05-16,674918,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Liberation. Whether They Want It Or Not.,6.9,78